### ISSUE TITLE
fuse: mount failed: Permission denied

### ISSUE THREAD

**Issue by jb-alvarado** [kdelfour/cloud9-docker#11]
Hello,I have problem to use the sftp function in cloud9. I get always the message:

```
An error occurred while creating the mount:
fuse: mount failed: Permission denied
```

I have check the user and group, and I also try to mount the folder in the cloud9 console with: `sshfs user@server:/ /mnt/tmp`, but is the same. On a different computer with a fresh install version from sshfs the connection works fine.

Have you any idea?

Regards

Jonathan

**Comment by jb-alvarado** [comment]
Ok found the solution:
```
docker run --privileged --cap-add=SYS_ADMIN --device=/dev/fuse [...]
```

**Comment by kdelfour** [comment]
@jb-alvarado Thanks for the solution, I will add it to the README.
