### ISSUE TITLE
Running the an app under development doesn't work

### ISSUE THREAD

**Issue by rajivkaggarwal** [kdelfour/cloud9-docker#2]
When launching/running a Nodejs app within cloud9 I find that the Nodejs app exits after the first request is handled.  Is this an issue with cloud9 being run via supervisor?  Or ???

cloud9 seems to operate find as and editor, etc.

**Comment by kdelfour** [comment]
Cloud9 v2 is no longer maintained. I'm going to migrate to Cloud9 3.0 SDK https://github.com/c9/core and I'm going to try if this problem is still present.

**Comment by kdelfour** [comment]
@rajivkaggarwal I have update to the latest version of Cloud9. Does it work now for you?
