### ISSUE TITLE
Dockerfile build problem

### ISSUE THREAD

**Issue by henrybear327** [kdelfour/cloud9-docker#4]
Hello,

Your Cloud9 docker container works like charm. I love it some much. But there is one issue while I tried to tweak it.

I tried building your Dockerfile, but I kept getting this error message "conf/cloud9.conf: no such file or directory."

I have no idea how this could be fixed and I am curious about how you made your build successful, could you give me some lead about this issue. 

Thanks.

**Comment by ycprog** [comment]
You need not just the Dockerfile but also the conf directory and the cloud9.conf file in it to build your c9 docker image

**Comment by kdelfour** [comment]
You're right @ycprog ,thanks you!
@henrybear327, you must have the dockerfile but also the conf directory to build your dockerfile.
