### ISSUE TITLE
Unable to test : network connection pb

### ISSUE THREAD

**Issue by revollat** [kdelfour/cloud9-docker#5]
I ran 

    docker run -it -d -p 8181:8181 kdelfour/cloud9-docker

So I have a running container : 

    9084bc7af42d        kdelfour/cloud9-docker:latest   "supervisord -c /etc   52 seconds ago      Up 51 seconds       0.0.0.0:8181->8181/tcp   naughty_nobel

With some process inside : 

```
$ docker exec -it 9084bc7af42d ps -aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.1  60532 13864 ?        Ss+  20:09   0:00 /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/s
root         7  0.3  0.2 699092 23608 ?        Sl   20:09   0:01 node /cloud9/server.js --listen 0.0.0.0 -w /workspace
root        13  0.0  0.0  15564  1152 ?        R+   20:14   0:00 ps -aux
$ 
```

But when I try to access the IDE from my browser : http://127.0.0.1:8181/ the connection can't be establish (like a TCP/IP level connection error). I tried on 2 different machines,  I also tried to build from source : same result ...
(I do not have firewall rules or something that could explain that). 

is it working for you ?

**Comment by xuxogarcia** [comment]
I have the same issue. It claims to be running but can't access it.

**Comment by xuxogarcia** [comment]
Figured it out....it needs authentication on the config file:

docker exec -it <CONTAINER_ID> vi /etc/supervisor/conf.d/cloud9.conf (look at line 2)

[program:cloud9]
command = node /cloud9/server.js --listen 0.0.0.0 -a user:password -w /workspace
directory = /cloud9
user = root
autostart = true
autorestart = true
stdout_logfile = /var/log/supervisor/cloud9.log
stderr_logfile = /var/log/supervisor/cloud9_errors.log
environment = NODE_ENV="production"

restart container! awesomeness awaits!
Thanks for dockerizing cloud9

**Comment by kdelfour** [comment]
Now it's not necessary to add --auth in cloud9.conf to test it.
