### ISSUE TITLE
preview of application

### ISSUE THREAD

**Issue by jmls** [kdelfour/cloud9-docker#7]
so, I've got c9 running , localhost:8181 works well and brings up the ide

however, when I run my app (node app.js) how can I preview it ? localhost:3000 (the port used) does not work - if I expose 3000 with -p on the docker startup line, I *can* access the app by using the mapped docker port

**Comment by cbeldacap** [comment]
@jmls This issue's a bit old, but do you remember if you found a solution?

**Comment by jmls** [comment]
sorry moved away from c9 when some of the licencing changed (before it was bought by amazon)
