### ISSUE TITLE
`amploader` module missing

### ISSUE THREAD

**Issue by ahxxm** [kdelfour/cloud9-docker#8]
and a module named `emmet`, sorry the two spell might be wrong, I can't exact remember... destroyed the virtual machine right after make c9 run.
npm install them then restart would fix(`npm insatll` won't install the loader)

**Comment by ahxxm** [comment]
feel great to write a bug report not mentioning platform or something btw..

**Comment by kdelfour** [comment]
I have rebuild a new container image and I have deployed this new image. 
For me, it's working very well.
Can you tell me if this new image resolved your problem?

**Comment by ahxxm** [comment]
yes it's working well, thanks!
